// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5_6u-6OEy6xvHWzyYpln8CYMADAGFRxI',
    appId: '1:461284927327:web:006b3695325f7d8f4438ea',
    messagingSenderId: '461284927327',
    projectId: 'crypto-list-app-d5d20',
    authDomain: 'crypto-list-app-d5d20.firebaseapp.com',
    storageBucket: 'crypto-list-app-d5d20.firebasestorage.app',
    measurementId: 'G-87LF4VP39S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr-yd92n0yy8iUFP00m-Q0pzfkmuMqcWk',
    appId: '1:461284927327:android:bbdc1542ec54f1f14438ea',
    messagingSenderId: '461284927327',
    projectId: 'crypto-list-app-d5d20',
    storageBucket: 'crypto-list-app-d5d20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgg4RRMnJ14yZd5XNmYG4uI8keUpipeSg',
    appId: '1:461284927327:ios:390bbcba7873d1794438ea',
    messagingSenderId: '461284927327',
    projectId: 'crypto-list-app-d5d20',
    storageBucket: 'crypto-list-app-d5d20.firebasestorage.app',
    iosBundleId: 'com.example.flutterRos1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgg4RRMnJ14yZd5XNmYG4uI8keUpipeSg',
    appId: '1:461284927327:ios:390bbcba7873d1794438ea',
    messagingSenderId: '461284927327',
    projectId: 'crypto-list-app-d5d20',
    storageBucket: 'crypto-list-app-d5d20.firebasestorage.app',
    iosBundleId: 'com.example.flutterRos1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5_6u-6OEy6xvHWzyYpln8CYMADAGFRxI',
    appId: '1:461284927327:web:d06691f4a89df8a14438ea',
    messagingSenderId: '461284927327',
    projectId: 'crypto-list-app-d5d20',
    authDomain: 'crypto-list-app-d5d20.firebaseapp.com',
    storageBucket: 'crypto-list-app-d5d20.firebasestorage.app',
    measurementId: 'G-TE85XMYLH7',
  );
}
